import {Dimensions} from 'react-native';
import {fontResize} from './fontResize';

const CONSTANTS = {
  TEXT: {
    MIND_TALKS: 'Mind Talks',
    YOUR_PATH: 'Your Path to Clarity',
    WELCOME_WORLD: 'WELCOME TO THE WORLD OF',
    PSYCHOLOGY: 'PSYCHOLOGY',
    MINDFULL: 'Mindful Insights',
    PERSONAL_GROWTH: 'Personal Growth',
    LOREM_TEXT:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    SIGN_IN_VIA: 'Sign in via mobile number',
    BACK: 'Back',
    YOUR_NUMBER: 'Your Phone Number',
    PHONE_NUMBER: 'Enter the phone number',
    ENTER_PHONE_NUMBER: 'Enter your phone number to get started.',
    MAKE_SURE:
      'Make sure you can receive SMS to this number so that wer can send you a code.',
    INVALID_PHONE_NUMBER: 'Please enter a valid phone number',
    VERIFICATION_CODE: 'Verification Code',
    VALID_VERIFICATION_CODE: 'Please enter valid verification code',
    PLEASE_ENTER_CODE:
      'Please enter the code we have sent to your phone number',
    EDIT_NUMBER: 'Edit number?',
    RESEND_CODE: 'Resend code',
    OR: 'Or',
    CONTINUE: 'Continue',
    PERSONAL_INFORMATION: 'Personal Information',
    CHAT_PSYCHOLOGIST: 'Connect with Psychologist',
    NAME: 'Name',
    ENTER_NAME: 'Enter your name',
    EMAIL_ADDRESS: 'Email Address',
    ENTER_EMAIL_ADDRESS: 'Enter email address',
    MOBILE_NUMBER: ' Mobile Number',
    DATE_BIRTH: 'Birth Date',
    SELECT_DATE: 'Select date',
    GENDER: 'Gender',
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
    SAVE_DETAILS: 'Save Details',
    CANCEL: 'CANCEL',
    OK: 'OK',
    CATEGORIES: 'CATEGORIES',
    TOP_CATEGORIES: 'Top Categories',
    TRENDING: 'Trending',
    ONLINE: 'Online',
    TOP_RATED_PSTCHOLOGIES: 'Top Rated  psychologies',
    BLAG: 'Blog',
    WHAT_OUR_CLIENTS: 'What our client says about us',
    CHAT_ASSISTANT: 'Chat with Assistant',
    SEND_GIFT_TO: 'Send gift to ',
    VERIFY: 'Verify',
    NEXT: 'Next',
    Skip: 'Skip',
    UPDATE: 'Update',
    LOGIN: 'Login',
    FIRST_NAME: 'First Name',
    DOB: 'Date Of Birth',
    BOOK_NOW: 'Book Now',
    OFFLINE: 'offline',
    CHAT: 'Chat',
    TOP_CHOICE: 'Top Choice',
    SIMILAR_CONSULTANTS: 'Similar Consultants',
    REVIEWS: 'REVIEWS',
    SETTING: 'SETTING',
    LOGOUT: 'LOGOUT',
    MY_APPOINTMENTS: 'My Appointments',
    RECHARGE: 'Recharge',
    SETTINGS: 'Settings',
    SERVICES: 'Services',
    RATE_US: 'Rate us',
    CUSTOMER_SUPPORT: 'Customer Support',
    DIGITAL_WALLET: 'Digital Wallet',
    SIGN_UP_PYCHOLOGIST: 'Sign up as Pychologist',
    WALLET: 'Wallet',
    CALLS: 'Calls',
    CALL: 'Call',
    SCHEDULE: 'Schedule',
    YOU_HAVE_OPTION:
      'You have the option to schedule a message or call; Otherwise, you can directly',
    NOW: 'Now',
    SCHEDULE_LOREM: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    FILTER: 'Filter',
    CLEAR_FILTER: 'Clear Filters',
    SORT_BY: 'Sort by',
    SKILL: 'Skill',
    LANGUAGE: 'Language',
    COUNTRY: 'Country',
    OFFER: 'Offer',
    PROCEED: 'Proceed',
    TOP_PSYCHOLOGIST: 'Top Psychologist',
    CHOOSE_PROFILE_PHOTO: 'Choose Profile Picture',
    CHOOSE_FROM_GALLERY: 'Choose from gallery',
    CHOOSE_FROM_CAMERA: 'Choose from camera',
    CANCEL: 'Cancel',
    CAMERA_PERMISSION: 'Camera Permission',
    PERMISSION_MESSAGE: 'App needs camera permission',
    NEW_USER: ' New user? ',
    LOG_IN: 'Log in',
    FORGOT_PASSWORD: 'Forgot\nPassword',
    I_ALREADY_ACCOUNT: 'I aleady have an account',
    CONTINUE_WITH_FACEBOOK: 'Continue with Facebook',
    CONTINUE_WITH_GOOGLE: 'Continue with Google',
    CONTINUE_WITH_APPLE: 'Continue with Apple',
    OR_CONTINUE_WITH: 'Or continue with',
    EMAIL: 'Email',
    Username: 'Username',
    SIGN_UP: 'Sign up',
    FORGOT_YOUR_PASSWORD: 'Forgot your password',
    LEARN_MORE: 'Learn more',
    TITLE: 'Title',
    CONDITION: 'Condition',
    ADD: 'Add',
    ACCEPT: 'Accept',
    REJECT: 'Reject',
    NEWS_FEED: 'News Feed',
    NEWS: 'News',
    MOST_POPULAR: 'Most Popular',
    VIEW_ALL: 'View all',
    SHORT: 'Short',
    ALERT_TITLE: 'Alert',
    YES: 'Yes',
    OK: 'OK',
    OKAY: 'Okay',
    DELETE: 'Delete',
    NO: 'No',
    SAVE: 'Save',
    NOTIFICATION: 'Notification',
    APPLY: 'Apply',
    TYPE_YOUR_MESSAGE: 'Type your message here',
    YOU_ALL_SET: 'You’re all set!',
    CURRENTLT_OFFLINE: name =>
      `${name} is currently offline. There may be a delay in our chat.`,
    AS_PER_WAIT: name =>
      `As you wait for ${name}, perhaps you could explore other psychologists and join their waitlists.`,
    IF_YOU_JOIN_WAITLIST: name =>
      `If you are join the waitlist, we will notify ${name} to take session, if possible.`,
    SELECT_LANGUAGE: 'Select Language',
    JOIN_WAITLIST: 'Join Waitlist',
    IS_OFFLINE_DELAY: name => `${name} is offline, Chat might get delayed.`,
    LEAVE_OF: name => `Leave waitlist of ${name}?`,
    INSTEAD_OF_LEAVING: name =>
      `Instead of leaving the waitlist of ${name}, you may also join the waitlist of these trending psychologist.`,
    LEAVE: 'Leave',
    SESSION_REMOVE: 'Session end',
    CANCEL_APPOINTMENT: 'Cancel Appointment',
    SESSION_REMOVE_IMAGE: 'Are you sure you want to end this session?',
    APPOINTMENT_REMOVE_IMAGE:
      'Are you sure you want to cancel this appointment?',
    ADDITIONAL_COMMENT: 'Additional Comments',
    RECHARGE_NOW: 'Recharge Now',
    MINIMUM: ({name, balance}) =>
      `Minimum balance of 5 minutes (INR ${
        Number(balance) * 5
      }) is required to start chat with ${name}`,
    SEARCH_TEXT: name => `Search “${name}”`,
    WALLET_TRANSACTIONS: 'Wallet Transactions',
    AVAILABLE_BALANCE: 'Available Balance',
    WITHDRAWAL: 'Withdrawal',
    WITHDEAWAL_REQUEST: 'Withdrawal Request',
    SUBMIT: 'Submit',
    ADD_MONEY: 'Add money to wallet',
    DELETE_ACCOUNT: 'Delete account',
    SESSION_EXPIRED: 'Session Expired',
    YOU_HAVE_LOGIN:
      'You are already login another system. If you have  using this functionality then please login?',
  },
  PERMISSION_MESSGAE: {
    PERMISSION_NOTITIFCATION_MESSAGE:
      'Please turn on notification permission manually',
    BLOCKED_PERMISSION: 'The permission is denied and not requestable anymore',
    CANNOT_OPEN: 'cannot open settings',
    GRANTED_PERMISSION: 'The permission is granted',
    LIMITED_PERMISSION: 'The permission is limited: some actions are possible',
    DENIED_PERMISSION:
      'The permission has not been requested / is denied but requestable',
    UNIAVAILABLE_PERMISSION:
      'This feature is not available (on this device / in this context)',
    BLOCK_USER_MESSAGE: 'You blocked this account. Tap to unblock',
  },
  STYLE_TYPE: {
    CANCEL: 'cancel',
    SUCCESS: 'success',
    ERROR: 'error',
    PADDING: 'padding',
  },
  ERROR_MESSAGE: {
    YOU_HAVE: 'You have',
    ATTEMPS_LEFT: 'attempts left',
    PASSWORD_EMAIL: 'Your password or email do not match',
    YOU_ARE_BLOCKED:
      'You are currently blocked from the app.Please start the pin recovery procedure.',
  },
  formik_Key: {
    PASSWORD: 'password',
    EMAIL_ADDRESS: 'emailAddress',
    FIRST_NAME: 'first_name',
    GENDER: 'gender',
    DOB: 'dateOfBirth',
    CONFIRM_PASSWORD: 'confirm_password',
    ENTER_PIN: 'enterPin',
    CONFIRM_PIN: 'confirmPin',
    CUREENT_PIN: 'cureentPin',
    NEW_PIN: 'newPin',
    CURRENT_PASSWORD: 'currentPassword',
    NEW_PASSWORD: 'newPassword',
    CONFIRM_PASSWORD: 'confirmPassword',
  },
  KEYBOARD_TYPE: {
    DEFAULT: 'default',
    NUMBER_PAD: 'number-pad',
    DECIMAL_PAD: 'decimal-pad',
    NUMERIC: 'numeric',
    EMAIL_ADDRESS: 'email-address',
    PHONE_PAD: 'phone-pad',
    URL: 'url',
  },

  STORAGE: {
    ISLOGGED: 'ISLOGGED',
    ISONBOARDING: 'ISONBOARDING',
    TOKEN: 'token',
    USER_DATA: 'USER_DATA',
    FCM_TOKEN: 'FCM_TOKEN',
    EMAIL: 'email',
    WAITLIST: 'WAITLIST',
    SIMILAR_LIST: 'SIMILAR_LIST',
    SCREEN_NAME: 'SCREEN',
    IS_UPDATE: 'IS_UPDATE',
  },
  SOCKET_EVENTS: {
    JOIN_ROOM: 'join_room',
    RECEIVE_MESSAGE: 'receive_message',
    SEND_MESSAGE: 'send_message',
    NOTIFICATION: 'notification',
  },
  THEME: {
    colors: {
      BLACK: '#000000',
      Dark_Gunmetal: '#1D2433',
      Light_Gray: 'rgba(29, 36, 51, 0.8)',
      PLATINUM_COLOR: '#E4E4E7',
      PRIMARY_COLOR: '#2F6FED',
      PRIMARY_ONE_COLOR: '#2F92ED',
      PRIMARY_SECOND_COLOR: '#1A5D9A',
      Light_Gunmetal: 'rgba(29, 36, 51, 0.65)',
      Light_Primary_Gunmetal: 'rgba(29, 36, 51, 0.8)',
      LIGHT_WHITE: '#E1E6EF',
      PRIMARY_COLORS: {
        100: '#F0F5FF',
      },
      NEUTRAL: {
        100: '#F8F9FC',
        200: '#F1F3F9',
        300: '#E1E6EF',
      },
      WHITE: {
        100: '#FFFFFF',
        0: 'rgba(255, 255, 255, 0)',
        20: 'rgba(255, 255, 255, 0.2)',
        40: 'rgba(255, 255, 255, 0.4)',
        50: 'rgba(255, 255, 255, 0.5)',
        60: 'rgba(255, 255, 255, 0.6)',
        80: 'rgba(255, 255, 255, 0.8)',
      },
      SECONDARY_COLOR: {
        80: 'rgba(29, 36, 51, 0.8)',
      },
      Disabled_Color: 'rgba(29, 36, 51, 0.65)',

      BackgroundColor: 'rgb(247,248,251)',
      MODAL_COLOR: 'rgba(29, 36, 51, 0.4)',
      DARK_GRAY_COLOR: '#1E1E1E',
      GRAY_COLOR: '#757575',
      WHITE_COLOR: '#fff',
      TRANSPARENT: 'transparent',
      YELLOW_COLOR: '#FFD400',
      RED: '#E02D3C',
      GRAY31: '#4F4F4F',
      GRAY11: '#1C1C1C',
      DARK_GRAY: '#a9a9a9',
      ORANGE: '#E5730B',
      MODAL_LIGHT_COLOR: 'rgba(0,0,0,0.4)',
      MODAL_BG_COLOR: 'rgba(0,0,0,0.7)',
      TRANSPARENT_5: 'rgba(0,0,0,.5)',
      GREEN: '#08875D',
      CHAT_PRIMARY_COLOR: '#D9E7FC',
      CHAT_SECONDARY_COLOR: '#FFFFFF',
      LIGHT_LINE_COLOR: {
        0: 'rgba(225, 230, 239, 0)',
        100: 'rgba(225, 230, 239, 1)',
      },
      DARK_ORANGE: '#FEF4EB',
    },
    typography: {
      fontFamily: {
        Bold: 'Lato-Bold',
        Light: 'Lato-Light',
        Black: 'Lato-Black',
        Regular: 'Lato-Regular',
        Hairline: 'Lato-Hairline',
      },
      fontWeights: {
        hairline: '100',
        thin: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
    },
    size: {
      WIDTH: Dimensions.get('window').width,
      HEIGHT: Dimensions.get('window').height,
      s2: fontResize(2),
      s3: fontResize(3),
      s4: fontResize(4),
      s6: fontResize(6),
      s8: fontResize(8),
      s10: fontResize(10),
      s12: fontResize(12),
      s14: fontResize(14),
      s16: fontResize(16),
      s18: fontResize(18),
      s20: fontResize(20),
      s22: fontResize(22),
      s24: fontResize(24),
      s26: fontResize(26),
      s28: fontResize(28),
      s30: fontResize(30),
      s32: fontResize(32),
      s34: fontResize(34),
      s36: fontResize(36),
      s38: fontResize(38),
      s40: fontResize(40),
      s42: fontResize(42),
      s44: fontResize(44),
      s46: fontResize(46),
      s48: fontResize(48),
      s50: fontResize(50),
      s60: fontResize(60),
      s70: fontResize(70),
      BUTTON_HEIGHT: fontResize(48),
      BUTTON_RADIUS: fontResize(8),
    },
  },
  PAYMENT: {
    //Razorpay key
    key: 'rzp_test_4rrCmYtqWUOUvT',
  },
};
export default CONSTANTS;
